//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.08 at 07:30:19 PM CEST 
//


package jaxbClasses;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for caloricUnitAttr.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="caloricUnitAttr">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="kcal"/>
 *     &lt;enumeration value="kj"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "caloricUnitAttr")
@XmlEnum
public enum CaloricUnitAttr {

    @XmlEnumValue("kcal")
    KCAL("kcal"),
    @XmlEnumValue("kj")
    KJ("kj");
    private final String value;

    CaloricUnitAttr(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CaloricUnitAttr fromValue(String v) {
        for (CaloricUnitAttr c: CaloricUnitAttr.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
