//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.25 at 03:53:27 AM CEST 
//


package JAXBClasses;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the JAXBClasses package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: JAXBClasses
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ProductType }
     * 
     */
    public ProductType createProductType() {
        return new ProductType();
    }

    /**
     * Create an instance of {@link ProductType.ProductInformation }
     * 
     */
    public ProductType.ProductInformation createProductTypeProductInformation() {
        return new ProductType.ProductInformation();
    }

    /**
     * Create an instance of {@link ProductType.ProductInformation.Nutrients }
     * 
     */
    public ProductType.ProductInformation.Nutrients createProductTypeProductInformationNutrients() {
        return new ProductType.ProductInformation.Nutrients();
    }

    /**
     * Create an instance of {@link ProductType.StockData }
     * 
     */
    public ProductType.StockData createProductTypeStockData() {
        return new ProductType.StockData();
    }

    /**
     * Create an instance of {@link ProductType.ProductInformation.Weight }
     * 
     */
    public ProductType.ProductInformation.Weight createProductTypeProductInformationWeight() {
        return new ProductType.ProductInformation.Weight();
    }

    /**
     * Create an instance of {@link ProductType.ProductInformation.Ingredients }
     * 
     */
    public ProductType.ProductInformation.Ingredients createProductTypeProductInformationIngredients() {
        return new ProductType.ProductInformation.Ingredients();
    }

    /**
     * Create an instance of {@link ProductType.ProductInformation.CurrentPrice }
     * 
     */
    public ProductType.ProductInformation.CurrentPrice createProductTypeProductInformationCurrentPrice() {
        return new ProductType.ProductInformation.CurrentPrice();
    }

    /**
     * Create an instance of {@link ProductType.ProductInformation.Nutrients.CaloricValue }
     * 
     */
    public ProductType.ProductInformation.Nutrients.CaloricValue createProductTypeProductInformationNutrientsCaloricValue() {
        return new ProductType.ProductInformation.Nutrients.CaloricValue();
    }

}
