//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.07 at 11:22:00 PM CEST 
//


package jaxbClasses;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jaxbClasses package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jaxbClasses
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ProfilesLOCAL }
     * 
     */
    public ProfilesLOCAL createProfilesLOCAL() {
        return new ProfilesLOCAL();
    }

    /**
     * Create an instance of {@link ProfilesLOCAL.Profile }
     * 
     */
    public ProfilesLOCAL.Profile createProfilesLOCALProfile() {
        return new ProfilesLOCAL.Profile();
    }
    
    /**
     * Create an instance of {@link Profiles }
     * 
     */
    public Profiles createProfiles() {
        return new Profiles();
    }

    /**
     * Create an instance of {@link Profiles.Profile }
     * 
     */
    public Profiles.Profile createProfilesProfile() {
        return new Profiles.Profile();
    }
    
     /**
     * Create an instance of {@link Profile }
     * 
     */
    public Profile createProfile() {
        return new Profile();
    }
    
     /**
     * Create an instance of {@link ProductTypesLOCAL }
     * 
     */
    public ProductTypesLOCAL createProductTypesLOCAL() {
        return new ProductTypesLOCAL();
    }

    /**
     * Create an instance of {@link ProductTypesLOCAL.ProductType }
     * 
     */
    public ProductTypesLOCAL.ProductType createProductTypesLOCALProductType() {
        return new ProductTypesLOCAL.ProductType();
    }

    /**
     * Create an instance of {@link ProductTypesLOCAL.ProductType.Nutrients }
     * 
     */
    public ProductTypesLOCAL.ProductType.Nutrients createProductTypesLOCALProductTypeNutrients() {
        return new ProductTypesLOCAL.ProductType.Nutrients();
    }

    /**
     * Create an instance of {@link ProductTypesLOCAL.ProductType.Weight }
     * 
     */
    public ProductTypesLOCAL.ProductType.Weight createProductTypesLOCALProductTypeWeight() {
        return new ProductTypesLOCAL.ProductType.Weight();
    }

    /**
     * Create an instance of {@link ProductTypesLOCAL.ProductType.Ingredients }
     * 
     */
    public ProductTypesLOCAL.ProductType.Ingredients createProductTypesLOCALProductTypeIngredients() {
        return new ProductTypesLOCAL.ProductType.Ingredients();
    }

    /**
     * Create an instance of {@link ProductTypesLOCAL.ProductType.CurrentPrice }
     * 
     */
    public ProductTypesLOCAL.ProductType.CurrentPrice createProductTypesLOCALProductTypeCurrentPrice() {
        return new ProductTypesLOCAL.ProductType.CurrentPrice();
    }

    /**
     * Create an instance of {@link ProductTypesLOCAL.ProductType.Nutrients.CaloricValue }
     * 
     */
    public ProductTypesLOCAL.ProductType.Nutrients.CaloricValue createProductTypesLOCALProductTypeNutrientsCaloricValue() {
        return new ProductTypesLOCAL.ProductType.Nutrients.CaloricValue();
    }
    

    
     /**
     * Create an instance of {@link ProductTypes }
     * 
     */
    public ProductTypes createProductTypes() {
        return new ProductTypes();
    }

    /**
     * Create an instance of {@link ProductTypes.ProductType }
     * 
     */
    public ProductTypes.ProductType createProductTypesProductType() {
        return new ProductTypes.ProductType();
    }
    
    /**
     * Create an instance of {@link ProductType }
     * 
     */
    public ProductType createProductType() {
        return new ProductType();
    }

    /**
     * Create an instance of {@link ProductType.Nutrients }
     * 
     */
    public ProductType.Nutrients createProductTypeNutrients() {
        return new ProductType.Nutrients();
    }

    /**
     * Create an instance of {@link ProductType.Weight }
     * 
     */
    public ProductType.Weight createProductTypeWeight() {
        return new ProductType.Weight();
    }

    /**
     * Create an instance of {@link ProductType.Ingredients }
     * 
     */
    public ProductType.Ingredients createProductTypeIngredients() {
        return new ProductType.Ingredients();
    }

    /**
     * Create an instance of {@link ProductType.CurrentPrice }
     * 
     */
    public ProductType.CurrentPrice createProductTypeCurrentPrice() {
        return new ProductType.CurrentPrice();
    }

    /**
     * Create an instance of {@link ProductType.Nutrients.CaloricValue }
     * 
     */
    public ProductType.Nutrients.CaloricValue createProductTypeNutrientsCaloricValue() {
        return new ProductType.Nutrients.CaloricValue();
    }
    
     public ProductsLOCAL createProductsLOCAL() {
        return new ProductsLOCAL();
    }

    /**
     * Create an instance of {@link ProductsLOCAL.Product }
     * 
     */
    public ProductsLOCAL.Product createProductsLOCALProduct() {
        return new ProductsLOCAL.Product();
    }

    /**
     * Create an instance of {@link ProductsLOCAL.Product.ProductType }
     * 
     */
    public ProductsLOCAL.Product.ProductType createProductsLOCALProductProductType() {
        return new ProductsLOCAL.Product.ProductType();
    }

    /**
     * Create an instance of {@link ProductsLOCAL.Product.Fridge }
     * 
     */
    public ProductsLOCAL.Product.Fridge createProductsLOCALProductFridge() {
        return new ProductsLOCAL.Product.Fridge();
    }

    /**
     * Create an instance of {@link ProductsLOCAL.Product.Profile }
     * 
     */
    public ProductsLOCAL.Product.Profile createProductsLOCALProductProfile() {
        return new ProductsLOCAL.Product.Profile();
    }

    /**
     * Create an instance of {@link ProductsLOCAL.Product.PriceWas }
     * 
     */
    public ProductsLOCAL.Product.PriceWas createProductsLOCALProductPriceWas() {
        return new ProductsLOCAL.Product.PriceWas();
    }
    
     public Products createProducts() {
        return new Products();
    }

    /**
     * Create an instance of {@link Products.Product }
     * 
     */
    public Products.Product createProductsProduct() {
        return new Products.Product();
    }

    /**
     * Create an instance of {@link Products.Product.ProductType }
     * 
     */
    public Products.Product.ProductType createProductsProductProductType() {
        return new Products.Product.ProductType();
    }
    
     /**
     * Create an instance of {@link Products.Product.InFridge }
     * 
     */
    public Products.Product.InFridge createProductsProductInFridge() {
        return new Products.Product.InFridge();
    }
    
     /**
     * Create an instance of {@link Product }
     * 
     */
    public Product createProduct() {
        return new Product();
    }

    /**
     * Create an instance of {@link Product.Owner }
     * 
     */
    public Product.Owner createProductOwner() {
        return new Product.Owner();
    }

    /**
     * Create an instance of {@link Product.ProductType }
     * 
     */
    public Product.ProductType createProductProductType() {
        return new Product.ProductType();
    }
    
    /**
     * Create an instance of {@link Product.InFridge }
     * 
     */
    public Product.InFridge createProductInFridge() {
        return new Product.InFridge();
    }

    /**
     * Create an instance of {@link Product.PriceWas }
     * 
     */
    public Product.PriceWas createProductPriceWas() {
        return new Product.PriceWas();
    }

    /**
     * Create an instance of {@link Product.Owner.Profile }
     * 
     */
    public Product.Owner.Profile createProductOwnerProfile() {
        return new Product.Owner.Profile();
    }
    
    /**
     * Create an instance of {@link NotificationsLOCAL }
     * 
     */
    public NotificationsLOCAL createNotificationsLOCAL() {
        return new NotificationsLOCAL();
    }

    /**
     * Create an instance of {@link NotificationsLOCAL.Notification }
     * 
     */
    public NotificationsLOCAL.Notification createNotificationsLOCALNotification() {
        return new NotificationsLOCAL.Notification();
    }

    /**
     * Create an instance of {@link NotificationsLOCAL.Notification.Profile }
     * 
     */
    public NotificationsLOCAL.Notification.Profile createNotificationsLOCALNotificationProfile() {
        return new NotificationsLOCAL.Notification.Profile();
    }
    
    public Notifications createNotifications() {
        return new Notifications();
    }

    /**
     * Create an instance of {@link Notifications.Notification }
     * 
     */
    public Notifications.Notification createNotificationsNotification() {
        return new Notifications.Notification();
    }

    /**
     * Create an instance of {@link Notifications.Notification.SendTo }
     * 
     */
    public Notifications.Notification.SendTo createNotificationsNotificationSendTo() {
        return new Notifications.Notification.SendTo();
    }

    /**
     * Create an instance of {@link Notifications.Notification.SendTo.Profile }
     * 
     */
    public Notifications.Notification.SendTo.Profile createNotificationsNotificationSendToProfile() {
        return new Notifications.Notification.SendTo.Profile();
    }
    
    /**
     * Create an instance of {@link Notification }
     * 
     */
    public Notification createNotification() {
        return new Notification();
    }

    /**
     * Create an instance of {@link Notification.SendTo }
     * 
     */
    public Notification.SendTo createNotificationSendTo() {
        return new Notification.SendTo();
    }

    /**
     * Create an instance of {@link Notification.SendTo.Profile }
     * 
     */
    public Notification.SendTo.Profile createNotificationSendToProfile() {
        return new Notification.SendTo.Profile();
    }
    
     /**
     * Create an instance of {@link FridgesLOCAL }
     * 
     */
    public FridgesLOCAL createFridgesLOCAL() {
        return new FridgesLOCAL();
    }

    /**
     * Create an instance of {@link FridgesLOCAL.Fridge }
     * 
     */
    public FridgesLOCAL.Fridge createFridgesLOCALFridge() {
        return new FridgesLOCAL.Fridge();
    }

    /**
     * Create an instance of {@link FridgesLOCAL.Fridge.ProductTypes }
     * 
     */
    public FridgesLOCAL.Fridge.ProductTypes createFridgesLOCALFridgeProductTypes() {
        return new FridgesLOCAL.Fridge.ProductTypes();
    }

    /**
     * Create an instance of {@link FridgesLOCAL.Fridge.ProductTypes.ProductType }
     * 
     */
    public FridgesLOCAL.Fridge.ProductTypes.ProductType createFridgesLOCALFridgeProductTypesProductType() {
        return new FridgesLOCAL.Fridge.ProductTypes.ProductType();
    }

    /**
     * Create an instance of {@link FridgesLOCAL.Fridge.ProductTypes.ProductType.Products }
     * 
     */
    public FridgesLOCAL.Fridge.ProductTypes.ProductType.Products createFridgesLOCALFridgeProductTypesProductTypeProducts() {
        return new FridgesLOCAL.Fridge.ProductTypes.ProductType.Products();
    }

    /**
     * Create an instance of {@link FridgesLOCAL.Fridge.Profiles }
     * 
     */
    public FridgesLOCAL.Fridge.Profiles createFridgesLOCALFridgeProfiles() {
        return new FridgesLOCAL.Fridge.Profiles();
    }

    /**
     * Create an instance of {@link FridgesLOCAL.Fridge.ProductTypes.ProductType.StockData }
     * 
     */
    public FridgesLOCAL.Fridge.ProductTypes.ProductType.StockData createFridgesLOCALFridgeProductTypesProductTypeStockData() {
        return new FridgesLOCAL.Fridge.ProductTypes.ProductType.StockData();
    }

    /**
     * Create an instance of {@link FridgesLOCAL.Fridge.ProductTypes.ProductType.Products.Product }
     * 
     */
    public FridgesLOCAL.Fridge.ProductTypes.ProductType.Products.Product createFridgesLOCALFridgeProductTypesProductTypeProductsProduct() {
        return new FridgesLOCAL.Fridge.ProductTypes.ProductType.Products.Product();
    }

    /**
     * Create an instance of {@link FridgesLOCAL.Fridge.Profiles.Profile }
     * 
     */
    public FridgesLOCAL.Fridge.Profiles.Profile createFridgesLOCALFridgeProfilesProfile() {
        return new FridgesLOCAL.Fridge.Profiles.Profile();
    }
    
    /**
     * Create an instance of {@link Fridges }
     * 
     */
    public Fridges createFridges() {
        return new Fridges();
    }

    /**
     * Create an instance of {@link Fridges.Fridge }
     * 
     */
    public Fridges.Fridge createFridgesFridge() {
        return new Fridges.Fridge();
    }
    
    /**
     * Create an instance of {@link Fridge }
     * 
     */
    public Fridge createFridge() {
        return new Fridge();
    }

    /**
     * Create an instance of {@link Fridge.ProductTypes }
     * 
     */
    public Fridge.ProductTypes createFridgeProductTypes() {
        return new Fridge.ProductTypes();
    }

    /**
     * Create an instance of {@link Fridge.ProductTypes.ProductType }
     * 
     */
    public Fridge.ProductTypes.ProductType createFridgeProductTypesProductType() {
        return new Fridge.ProductTypes.ProductType();
    }

    /**
     * Create an instance of {@link Fridge.ProductTypes.ProductType.Products }
     * 
     */
    public Fridge.ProductTypes.ProductType.Products createFridgeProductTypesProductTypeProducts() {
        return new Fridge.ProductTypes.ProductType.Products();
    }

    /**
     * Create an instance of {@link Fridge.Profiles }
     * 
     */
    public Fridge.Profiles createFridgeProfiles() {
        return new Fridge.Profiles();
    }

    /**
     * Create an instance of {@link Fridge.ProductTypes.ProductType.StockData }
     * 
     */
    public Fridge.ProductTypes.ProductType.StockData createFridgeProductTypesProductTypeStockData() {
        return new Fridge.ProductTypes.ProductType.StockData();
    }

    /**
     * Create an instance of {@link Fridge.ProductTypes.ProductType.Products.Product }
     * 
     */
    public Fridge.ProductTypes.ProductType.Products.Product createFridgeProductTypesProductTypeProductsProduct() {
        return new Fridge.ProductTypes.ProductType.Products.Product();
    }

    /**
     * Create an instance of {@link Fridge.Profiles.Profile }
     * 
     */
    public Fridge.Profiles.Profile createFridgeProfilesProfile() {
        return new Fridge.Profiles.Profile();
    }
}