//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.13 at 10:12:19 PM CEST 
//


package JAXBClasses;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the JAXBClasses package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: JAXBClasses
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Profile }
     * 
     */
    public Profile createProfile() {
        return new Profile();
    }

    /**
     * Create an instance of {@link Profile.RecentConsumedProducts }
     * 
     */
    public Profile.RecentConsumedProducts createProfileRecentConsumedProducts() {
        return new Profile.RecentConsumedProducts();
    }

    /**
     * Create an instance of {@link Profile.RecentBoughtProducts }
     * 
     */
    public Profile.RecentBoughtProducts createProfileRecentBoughtProducts() {
        return new Profile.RecentBoughtProducts();
    }

    /**
     * Create an instance of {@link Profile.RecentConsumedProducts.Product }
     * 
     */
    public Profile.RecentConsumedProducts.Product createProfileRecentConsumedProductsProduct() {
        return new Profile.RecentConsumedProducts.Product();
    }

    /**
     * Create an instance of {@link Profile.RecentBoughtProducts.Product }
     * 
     */
    public Profile.RecentBoughtProducts.Product createProfileRecentBoughtProductsProduct() {
        return new Profile.RecentBoughtProducts.Product();
    }

}
