//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.14 at 01:25:07 AM CEST 
//


package JAXBClasses;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the JAXBClasses package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: JAXBClasses
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FrigdeManagerStorage }
     * 
     */
    public FrigdeManagerStorage createFrigdeManagerStorage() {
        return new FrigdeManagerStorage();
    }

    /**
     * Create an instance of {@link FrigdeManagerStorage.Profiles }
     * 
     */
    public FrigdeManagerStorage.Profiles createFrigdeManagerStorageProfiles() {
        return new FrigdeManagerStorage.Profiles();
    }

    /**
     * Create an instance of {@link FrigdeManagerStorage.Profiles.Profile }
     * 
     */
    public FrigdeManagerStorage.Profiles.Profile createFrigdeManagerStorageProfilesProfile() {
        return new FrigdeManagerStorage.Profiles.Profile();
    }

}
