//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.26 at 12:01:38 AM CEST 
//


package jaxbClasses;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jaxbClasses package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jaxbClasses
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ProductTypesLOCAL }
     * 
     */
    public ProductTypesLOCAL createProductTypesLOCAL() {
        return new ProductTypesLOCAL();
    }

    /**
     * Create an instance of {@link ProductTypesLOCAL.ProductType }
     * 
     */
    public ProductTypesLOCAL.ProductType createProductTypesLOCALProductType() {
        return new ProductTypesLOCAL.ProductType();
    }

    /**
     * Create an instance of {@link ProductTypesLOCAL.ProductType.StockData }
     * 
     */
    public ProductTypesLOCAL.ProductType.StockData createProductTypesLOCALProductTypeStockData() {
        return new ProductTypesLOCAL.ProductType.StockData();
    }
    
    /**
     * Create an instance of {@link ProductInformationLOCAL }
     * 
     */
    public ProductInformationLOCAL createProductInformationLOCAL() {
        return new ProductInformationLOCAL();
    }
    
     /**
     * Create an instance of {@link ProfilesLOCAL }
     * 
     */
    public ProfilesLOCAL createProfilesLOCAL() {
        return new ProfilesLOCAL();
    }

    /**
     * Create an instance of {@link ProfilesLOCAL.Profile }
     * 
     */
    public ProfilesLOCAL.Profile createProfilesLOCALProfile() {
        return new ProfilesLOCAL.Profile();
    }
    
     /**
     * Create an instance of {@link ProductsLOCAL }
     * 
     */
    public ProductsLOCAL createProductsLOCAL() {
        return new ProductsLOCAL();
    }

    /**
     * Create an instance of {@link ProductsLOCAL.Product }
     * 
     */
    public ProductsLOCAL.Product createProductsLOCALProduct() {
        return new ProductsLOCAL.Product();
    }

    /**
     * Create an instance of {@link ProductsLOCAL.Product.PriceWas }
     * 
     */
    public ProductsLOCAL.Product.PriceWas createProductsLOCALProductPriceWas() {
        return new ProductsLOCAL.Product.PriceWas();
    }
    
	/**
     * Create an instance of {@link Products }
     * 
     */
    public Products createProducts() {
        return new Products();
    }

    /**
     * Create an instance of {@link Products.Product }
     * 
     */
    public Products.Product createProductsProduct() {
        return new Products.Product();
    }

    /**
     * Create an instance of {@link Products.Product.Name }
     * 
     */
    public Products.Product.Name createProductsProductName() {
        return new Products.Product.Name();
    }
    
    public Product createProduct() {
        return new Product();
    }

    /**
     * Create an instance of {@link Product.Name }
     * 
     */
    public Product.Name createProductName() {
        return new Product.Name();
    }

    /**
     * Create an instance of {@link Product.Owner }
     * 
     */
    public Product.Owner createProductOwner() {
        return new Product.Owner();
    }

    /**
     * Create an instance of {@link Product.PriceWas }
     * 
     */
    public Product.PriceWas createProductPriceWas() {
        return new Product.PriceWas();
    }
    
}
