//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.25 at 06:10:42 PM CEST 
//


package jaxbClasses;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="productInformation">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="weight">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
 *                           &lt;attribute name="unit" use="required" type="{http://meinnamespace.meinefirma.de}weightUnitAttr" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ingredients">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ingredient" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="nutrients">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="caloricValue">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
 *                                     &lt;attribute name="unit" use="required" type="{http://meinnamespace.meinefirma.de}caloricUnitAttr" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="protein" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="carbohydrates" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="ofwichsugar" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="fat" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="ofwichsaturates" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="roughage" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="sodium" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="currentPrice">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
 *                           &lt;attribute name="currency" use="required" type="{http://meinnamespace.meinefirma.de}currencyAttr" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="barcode" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="stockData">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="stock" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="minstock" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "productInformation",
    "stockData"
})
@XmlRootElement(name = "productType")
public class ProductType {

    @XmlElement(required = true)
    protected ProductType.ProductInformation productInformation;
    @XmlElement(required = true)
    protected ProductType.StockData stockData;

    /**
     * Gets the value of the productInformation property.
     * 
     * @return
     *     possible object is
     *     {@link ProductType.ProductInformation }
     *     
     */
    public ProductType.ProductInformation getProductInformation() {
        return productInformation;
    }

    /**
     * Sets the value of the productInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductType.ProductInformation }
     *     
     */
    public void setProductInformation(ProductType.ProductInformation value) {
        this.productInformation = value;
    }

    /**
     * Gets the value of the stockData property.
     * 
     * @return
     *     possible object is
     *     {@link ProductType.StockData }
     *     
     */
    public ProductType.StockData getStockData() {
        return stockData;
    }

    /**
     * Sets the value of the stockData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductType.StockData }
     *     
     */
    public void setStockData(ProductType.StockData value) {
        this.stockData = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="weight">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
     *                 &lt;attribute name="unit" use="required" type="{http://meinnamespace.meinefirma.de}weightUnitAttr" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ingredients">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ingredient" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="nutrients">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="caloricValue">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
     *                           &lt;attribute name="unit" use="required" type="{http://meinnamespace.meinefirma.de}caloricUnitAttr" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="protein" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="carbohydrates" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="ofwichsugar" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="fat" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="ofwichsaturates" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="roughage" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="sodium" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="currentPrice">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
     *                 &lt;attribute name="currency" use="required" type="{http://meinnamespace.meinefirma.de}currencyAttr" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="barcode" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "weight",
        "description",
        "ingredients",
        "nutrients",
        "currentPrice",
        "barcode"
    })
    public static class ProductInformation {

        @XmlElement(required = true)
        protected String name;
        @XmlElement(required = true)
        protected ProductType.ProductInformation.Weight weight;
        @XmlElement(required = true)
        protected String description;
        @XmlElement(required = true)
        protected ProductType.ProductInformation.Ingredients ingredients;
        @XmlElement(required = true)
        protected ProductType.ProductInformation.Nutrients nutrients;
        @XmlElement(required = true)
        protected ProductType.ProductInformation.CurrentPrice currentPrice;
        @XmlElement(required = true)
        protected BigInteger barcode;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the weight property.
         * 
         * @return
         *     possible object is
         *     {@link ProductType.ProductInformation.Weight }
         *     
         */
        public ProductType.ProductInformation.Weight getWeight() {
            return weight;
        }

        /**
         * Sets the value of the weight property.
         * 
         * @param value
         *     allowed object is
         *     {@link ProductType.ProductInformation.Weight }
         *     
         */
        public void setWeight(ProductType.ProductInformation.Weight value) {
            this.weight = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the ingredients property.
         * 
         * @return
         *     possible object is
         *     {@link ProductType.ProductInformation.Ingredients }
         *     
         */
        public ProductType.ProductInformation.Ingredients getIngredients() {
            return ingredients;
        }

        /**
         * Sets the value of the ingredients property.
         * 
         * @param value
         *     allowed object is
         *     {@link ProductType.ProductInformation.Ingredients }
         *     
         */
        public void setIngredients(ProductType.ProductInformation.Ingredients value) {
            this.ingredients = value;
        }

        /**
         * Gets the value of the nutrients property.
         * 
         * @return
         *     possible object is
         *     {@link ProductType.ProductInformation.Nutrients }
         *     
         */
        public ProductType.ProductInformation.Nutrients getNutrients() {
            return nutrients;
        }

        /**
         * Sets the value of the nutrients property.
         * 
         * @param value
         *     allowed object is
         *     {@link ProductType.ProductInformation.Nutrients }
         *     
         */
        public void setNutrients(ProductType.ProductInformation.Nutrients value) {
            this.nutrients = value;
        }

        /**
         * Gets the value of the currentPrice property.
         * 
         * @return
         *     possible object is
         *     {@link ProductType.ProductInformation.CurrentPrice }
         *     
         */
        public ProductType.ProductInformation.CurrentPrice getCurrentPrice() {
            return currentPrice;
        }

        /**
         * Sets the value of the currentPrice property.
         * 
         * @param value
         *     allowed object is
         *     {@link ProductType.ProductInformation.CurrentPrice }
         *     
         */
        public void setCurrentPrice(ProductType.ProductInformation.CurrentPrice value) {
            this.currentPrice = value;
        }

        /**
         * Gets the value of the barcode property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getBarcode() {
            return barcode;
        }

        /**
         * Sets the value of the barcode property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setBarcode(BigInteger value) {
            this.barcode = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
         *       &lt;attribute name="currency" use="required" type="{http://meinnamespace.meinefirma.de}currencyAttr" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class CurrentPrice {

            @XmlValue
            protected float value;
            @XmlAttribute(name = "currency", required = true)
            protected CurrencyAttr currency;

            /**
             * Gets the value of the value property.
             * 
             */
            public float getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             */
            public void setValue(float value) {
                this.value = value;
            }

            /**
             * Gets the value of the currency property.
             * 
             * @return
             *     possible object is
             *     {@link CurrencyAttr }
             *     
             */
            public CurrencyAttr getCurrency() {
                return currency;
            }

            /**
             * Sets the value of the currency property.
             * 
             * @param value
             *     allowed object is
             *     {@link CurrencyAttr }
             *     
             */
            public void setCurrency(CurrencyAttr value) {
                this.currency = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ingredient" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "ingredient"
        })
        public static class Ingredients {

            @XmlElement(required = true)
            protected List<String> ingredient;

            /**
             * Gets the value of the ingredient property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the ingredient property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getIngredient().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getIngredient() {
                if (ingredient == null) {
                    ingredient = new ArrayList<String>();
                }
                return this.ingredient;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="caloricValue">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
         *                 &lt;attribute name="unit" use="required" type="{http://meinnamespace.meinefirma.de}caloricUnitAttr" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="protein" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="carbohydrates" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="ofwichsugar" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="fat" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="ofwichsaturates" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="roughage" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="sodium" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "caloricValue",
            "protein",
            "carbohydrates",
            "ofwichsugar",
            "fat",
            "ofwichsaturates",
            "roughage",
            "sodium"
        })
        public static class Nutrients {

            @XmlElement(required = true)
            protected ProductType.ProductInformation.Nutrients.CaloricValue caloricValue;
            protected float protein;
            protected float carbohydrates;
            protected float ofwichsugar;
            protected float fat;
            protected float ofwichsaturates;
            protected float roughage;
            protected float sodium;

            /**
             * Gets the value of the caloricValue property.
             * 
             * @return
             *     possible object is
             *     {@link ProductType.ProductInformation.Nutrients.CaloricValue }
             *     
             */
            public ProductType.ProductInformation.Nutrients.CaloricValue getCaloricValue() {
                return caloricValue;
            }

            /**
             * Sets the value of the caloricValue property.
             * 
             * @param value
             *     allowed object is
             *     {@link ProductType.ProductInformation.Nutrients.CaloricValue }
             *     
             */
            public void setCaloricValue(ProductType.ProductInformation.Nutrients.CaloricValue value) {
                this.caloricValue = value;
            }

            /**
             * Gets the value of the protein property.
             * 
             */
            public float getProtein() {
                return protein;
            }

            /**
             * Sets the value of the protein property.
             * 
             */
            public void setProtein(float value) {
                this.protein = value;
            }

            /**
             * Gets the value of the carbohydrates property.
             * 
             */
            public float getCarbohydrates() {
                return carbohydrates;
            }

            /**
             * Sets the value of the carbohydrates property.
             * 
             */
            public void setCarbohydrates(float value) {
                this.carbohydrates = value;
            }

            /**
             * Gets the value of the ofwichsugar property.
             * 
             */
            public float getOfwichsugar() {
                return ofwichsugar;
            }

            /**
             * Sets the value of the ofwichsugar property.
             * 
             */
            public void setOfwichsugar(float value) {
                this.ofwichsugar = value;
            }

            /**
             * Gets the value of the fat property.
             * 
             */
            public float getFat() {
                return fat;
            }

            /**
             * Sets the value of the fat property.
             * 
             */
            public void setFat(float value) {
                this.fat = value;
            }

            /**
             * Gets the value of the ofwichsaturates property.
             * 
             */
            public float getOfwichsaturates() {
                return ofwichsaturates;
            }

            /**
             * Sets the value of the ofwichsaturates property.
             * 
             */
            public void setOfwichsaturates(float value) {
                this.ofwichsaturates = value;
            }

            /**
             * Gets the value of the roughage property.
             * 
             */
            public float getRoughage() {
                return roughage;
            }

            /**
             * Sets the value of the roughage property.
             * 
             */
            public void setRoughage(float value) {
                this.roughage = value;
            }

            /**
             * Gets the value of the sodium property.
             * 
             */
            public float getSodium() {
                return sodium;
            }

            /**
             * Sets the value of the sodium property.
             * 
             */
            public void setSodium(float value) {
                this.sodium = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
             *       &lt;attribute name="unit" use="required" type="{http://meinnamespace.meinefirma.de}caloricUnitAttr" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class CaloricValue {

                @XmlValue
                protected float value;
                @XmlAttribute(name = "unit", required = true)
                protected CaloricUnitAttr unit;

                /**
                 * Gets the value of the value property.
                 * 
                 */
                public float getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 */
                public void setValue(float value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the unit property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link CaloricUnitAttr }
                 *     
                 */
                public CaloricUnitAttr getUnit() {
                    return unit;
                }

                /**
                 * Sets the value of the unit property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link CaloricUnitAttr }
                 *     
                 */
                public void setUnit(CaloricUnitAttr value) {
                    this.unit = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
         *       &lt;attribute name="unit" use="required" type="{http://meinnamespace.meinefirma.de}weightUnitAttr" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Weight {

            @XmlValue
            protected float value;
            @XmlAttribute(name = "unit", required = true)
            protected WeightUnitAttr unit;

            /**
             * Gets the value of the value property.
             * 
             */
            public float getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             */
            public void setValue(float value) {
                this.value = value;
            }

            /**
             * Gets the value of the unit property.
             * 
             * @return
             *     possible object is
             *     {@link WeightUnitAttr }
             *     
             */
            public WeightUnitAttr getUnit() {
                return unit;
            }

            /**
             * Sets the value of the unit property.
             * 
             * @param value
             *     allowed object is
             *     {@link WeightUnitAttr }
             *     
             */
            public void setUnit(WeightUnitAttr value) {
                this.unit = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="stock" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="minstock" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "stock",
        "minstock"
    })
    public static class StockData {

        protected int stock;
        protected int minstock;

        /**
         * Gets the value of the stock property.
         * 
         */
        public int getStock() {
            return stock;
        }

        /**
         * Sets the value of the stock property.
         * 
         */
        public void setStock(int value) {
            this.stock = value;
        }

        /**
         * Gets the value of the minstock property.
         * 
         */
        public int getMinstock() {
            return minstock;
        }

        /**
         * Sets the value of the minstock property.
         * 
         */
        public void setMinstock(int value) {
            this.minstock = value;
        }

    }

}
